#global:
#  scrape_interval: 3s
#
##  external_labels:
##    monitor: "example-app"
##
##rule_files:
#
##scrape_configs:
##  - job_name: "prometheus_app"
##    static_configs:
##      - targets: ["localhost:9090"]
##
##  - job_name: "node-exporter"
##    static_configs:
##      - targets: ["node-exporter:9100"]
##
##  - job_name: "python-app"
##    static_configs:
##      - targets: ["flask-app:8080"]
#
#
#scrape_configs:
#  - job_name: "prometheus_app"
#    static_configs:
#      - targets: ["localhost:5000"]

global:
  scrape_interval: 3s

  external_labels:
    monitor: "example-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "example"
    static_configs:
      - targets: ["app:5000"]