name: Test - Unit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup environment
        run: |
          python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Unit Tests
        run: |
          cd src/tests
          python -m test_all_unit_tests
      - name: Run Integration Tests
        run: |
          cd src/tests
          python -m test_all_unit_tests
          python -m test_all_integration_tests